name: lab_7_406787_test

on:
  push:
    branches:
      - lab_7/my_branch_406787

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install libs for testing
      run: |
        pip install pytest

    - name: prepare environment
      run: |
        cd ./env_406787 && python -m pip install -r requirements.txt

    - name: Run test
      run: |
        cd ./env_406787 && pytest calculator_test.py
